In [3]:
import pandas as pd

In [7]:
data = pd.read_csv("data/Registered_Business_Locations_-_San_Francisco.csv")

/Users/GaelGil/Desktop/GitRepos/Sneaker-Scraper/env/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (12,13,14,15,21,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
data.head(10)

,Location Id,Business Account Number,Ownership Name,DBA Name,Street Address,City,State,Source Zipcode,Business Start Date,Business End Date,...,NAICS Code,NAICS Code Description,Parking Tax,Transient Occupancy Tax,LIC Code,LIC Code Description,Supervisor District,Neighborhoods - Analysis Boundaries,Business Corridor,Business Location
0,1103593-08-161,1049564,Anjan Rajbhandari,Uber,28134 Harvey Ave,Hayward,CA,94544.0,03/24/2014,12/31/2017,...,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN
1,1218784-04-191,1100756,Luisa Alberto,High Five Sf,467 14th St,San Francisco,CA,94103.0,04/15/2019,04/15/2019,...,NaN,NaN,False,False,NaN,NaN,8.0,Mission,NaN,NaN
2,1223199-05-191,1102424,"Sunrun, Inc.","Sunrun, Inc",595 Market St,San Francisco,CA,94105.0,06/01/2008,06/01/2008,...,2200-2299,Utilities,False,False,NaN,NaN,NaN,NaN,NaN,NaN
3,1220748-05-191,1101579,Felix Hernandez,Tru-Tec Electric,44 Mcaker Ct,San Mateo,CA,94403.0,05/06/2019,06/18/2019,...,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN
4,1135452-02-171,1065102,Tirta Llc,Tirta,105 Hudson St 6s,New York City,NY,10013.0,06/09/2016,12/23/2018,...,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN
5,1157686-08-171,1074591,Alice Ho,Little Kite,3515 20th St,San Francisco,CA,94110.0,08/10/2017,12/31/2018,...,7220-7229,Food Services,False,False,H26,NaN,NaN,NaN,NaN,NaN
6,1131829-01-171,1063275,Outwork Inc,Outwork San Francisco,645 Harrison St,San Francisco,CA,94133.0,04/01/2016,12/31/2017,...,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN
7,1221744-05-191,1101933,Ava Tours Llc,Ava Voyage,880 Southgate Ave,Daly City,CA,94015.0,04/30/2019,04/30/2019,...,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN
8,1222244-05-191,1102118,Evgo Ride Share,Evgo Ride Share Services,1160 Mission St,San Francisco,CA,94103.0,05/18/2019,05/18/2019,...,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN
9,1230322-08-191,1105226,Elka Duran,Elka Duran,98 Belmar Ave,Daly City,CA,94015.0,12/01/2017,06/01/2018,...,NaN,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255033 entries, 0 to 255032
Data columns (total 26 columns):
Location Id                            255033 non-null object
Business Account Number                255033 non-null int64
Ownership Name                         255033 non-null object
DBA Name                               255033 non-null object
Street Address                         255029 non-null object
City                                   254842 non-null object
State                                  254417 non-null object
Source Zipcode                         254766 non-null float64
Business Start Date                    255032 non-null object
Business End Date                      101828 non-null object
Location Start Date                    255032 non-null object
Location End Date                      127446 non-null object
Mail Address                           158578 non-null object
Mail City                              153179 non-null object
Mail Zipcode                           153156 non-null object
Mail State                             153153 non-null object
NAICS Code                             159542 non-null object
NAICS Code Description                 159542 non-null object
Parking Tax                            255033 non-null bool
Transient Occupancy Tax                255033 non-null bool
LIC Code                               16988 non-null object
LIC Code Description                   15016 non-null object
Supervisor District                    151526 non-null float64
Neighborhoods - Analysis Boundaries    151521 non-null object
Business Corridor                      327 non-null object
Business Location                      167333 non-null object
dtypes: bool(2), float64(2), int64(1), object(21)
memory usage: 47.2+ MB

In [16]:
data.astype({'Business Location': 'object'}).dtypes
data.astype({'Business Location': 'object'}).dtypes
data.astype({'Business Location': 'object'}).dtypes
data.astype({'Business Location': 'object'}).dtypes
data.astype({'Business Location': 'object'}).dtypes

Location Id                             object
Business Account Number                  int64
Ownership Name                          object
DBA Name                                object
Street Address                          object
City                                    object
State                                   object
Source Zipcode                         float64
Business Start Date                     object
Business End Date                       object
Location Start Date                     object
Location End Date                       object
Mail Address                            object
Mail City                               object
Mail Zipcode                            object
Mail State                              object
NAICS Code                              object
NAICS Code Description                  object
Parking Tax                               bool
Transient Occupancy Tax                   bool
LIC Code                                object
LIC Code Description                    object
Supervisor District                    float64
Neighborhoods - Analysis Boundaries     object
Business Corridor                       object
Business Location                       object
dtype: object

In [17]:
data['Business Location']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
255028    NaN
255029    NaN
255030    NaN
255031    NaN
255032    NaN
Name: Business Location, Length: 255033, dtype: object

In [18]:
data.loc[40009]

Location Id                                            0454420-01-999
Business Account Number                                        454420
Ownership Name                         Acrf Construction Services Inc
DBA Name                               Acrf Construction Services Inc
Street Address                                       4929 Sunshine Ln
City                                                       Sacramento
State                                                              CA
Source Zipcode                                                  95841
Business Start Date                                        11/30/2010
Business End Date                                          04/20/2015
Location Start Date                                        11/30/2010
Location End Date                                          04/20/2015
Mail Address                                                      NaN
Mail City                                                         NaN
Mail Zipcode                                                      NaN
Mail State                                                        NaN
NAICS Code                                                        NaN
NAICS Code Description                                            NaN
Parking Tax                                                     False
Transient Occupancy Tax                                         False
LIC Code                                                          NaN
LIC Code Description                                              NaN
Supervisor District                                               NaN
Neighborhoods - Analysis Boundaries                               NaN
Business Corridor                                                 NaN
Business Location                       POINT (-121.347458 38.657859)
Name: 40009, dtype: object